### ISSUE TITLE
redirect of non secure https

### ISSUE THREAD

**Issue by Sopor-** [cadeyrn/bookmarks-organizer#101]
If the site have a not secure https the redirect doesn't work.

So for this address `http://www.handladesign.se` it will show that this site doesn't exists and it will be deleted. Instead it should show a message that there is a redirect, but it isn't secure. It should also be a warning instead of an error.

**Comment by cadeyrn** [comment]
Hi,

http://www.handladesign.se redirects to https://www.handladesign.se/ and this site is broken because of an invalid certificate. So it's the expected result that this bookmark will be marked as error. It's not a redirect to an insecure website, it's a redirect to a broken website.

**Comment by Sopor-** [comment]
I get the same behavior on this URL `http://twitter.com/TeamJungle`, it will be marked as error even if it redirects to `https://twitter.com/TeamJungle`

Another one that also will be marked as error is `http://h30434.www3.hp.com/t5/Windows-7-Beta-and-test/Validity-Sensor-finger-print-reader-and-windows-7/m-p/185507`. It redirects to an https and it will also redirect to another URL but it is still working. So i can't relay on Bookmark organizer and i need to check every URL before i delete them :(

**Comment by Sopor-** [comment]
Another one marked as error `http://www.ibm.com/developerworks/aix/library/au-tunnelingssh/index.html`
