### ISSUE TITLE
Disable confirmation messages should work without rescanning all bookmarks

### ISSUE THREAD

**Issue by Sopor-** [cadeyrn/bookmarks-organizer#103]
The `Disable confirmation messages` doesn't seems to work on an existing B-O search. To make the option to work i need to rescan all my 1500+ bookmarks. If i have a lot of bookmarks to add to whitelist i should be able to easy change the option and then back again, but for me to do that i need to rescan all bookmarks.

Maybe you could move the `Disable confirmation messages (not recommended)` to the B-O to the right of the `Errors` and `Warnings` checkmarks? That would make it easy to change it :)

If not, you should at least have more than one `Disable confirmation messages` for `add to whitelist`, `correct redirect` and `delete`.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 3.1 has been released with the following improvement:

> The Disable confirmation messages doesn't seems to work on an existing B-O search. To make the option to work i need to rescan all my 1500+ bookmarks. If i have a lot of bookmarks to add to whitelist i should be able to easy change the option and then back again, but for me to do that i need to rescan all bookmarks.
