### ISSUE TITLE
Bookmarks database corrupt after using Bookmarks Organizer

### ISSUE THREAD

**Issue by Gitoffthelawn** [cadeyrn/bookmarks-organizer#105]
I dislike having to report this, because you've made so many great improvements to Bookmarks Organizer, but I think I've found a *very* serious issue.

I noticed that when typing text into FF's urlbar, sometimes bookmarks would appear that had been deleted, updated, or edited by Bookmarks Organizer.  The thing is, that after Bookmark Organizer's deletion, update, or edit, FF should no longer be matching anything to that text.

To eliminate the problem, I exported all bookmarks (in JSON format), deleted all FF bookmark-related sqlite databases (including the new favicon sqlite database), and then imported the bookmarks back in.  Now searching in the urlbar works as expected.  I did find a serious bug in FF related to import/export, but it has nothing to do with Bookmarks Organizer (nor does it impact it), so I won't delve into that here.

I then used Bookmarks Organizer 3.0 to delete, edit, and update some bookmarks.  Again, typing text into the urlbar would cause some bookmarks to appear that should no longer match anything.

Things then got worse.  I typed into the urlbar a portion of a URL that was for a bookmark that I deleted using Bookmarks Organizer.  What happened next shocked me.  FF matched the text with a completely unrelated bookmark in the urlbar dropdown.  Clicking on that bookmark in the urlbar dropdown then loaded the URL for a bookmark that Bookmarks Organizer deleted!  Yikes!  Clearly the bookmarks database is corrupt again.  And the only thing that I did was run Bookmarks Organizer.  :(

As a contrived example, let's say I had a bookmark for `https://example-never-registered-00000.com`.   Bookmarks Organizer then found that this bookmark was no longer valid, and so I instructed Bookmarks Organizer to delete the bookmark.  Then when I type `never-registered` into the urlbar, a completely unrelated bookmark appears, but clicking on it goes to `https://example-never-registered-00000.com`!

I have no idea if this is a serious bug in Bookmarks Organizer, or if the bug is in Firefox itself, and is simply being exposed by using Bookmarks Organizer.

All testing was performed on FF 64.0 64-bit with Bookmarks Organizer 3.0.  Note that some of these problems were likely present before v3.0, but I hadn't isolated the issue to be related to Bookmarks Organizer until just now.

I dislike being the bearer of bad news, but I sincerely hope this information helps you.  :-)

**Comment by cadeyrn** [comment]
If you think that some behaviour after a removing or updating a bookmark is wrong then it's a bug in Firefox, not in Bookmarks Organizer. Bookmarks Organizer uses WebExtension APIs and has nothing to do with the address bar of Firefox at all.

**Comment by Gitoffthelawn** [comment]
@cadeyrn Do you know, for performing all bookmarks-related tasks, if FF itself uses the same Bookmarks API as extensions use?

**Comment by cadeyrn** [comment]
I don't know the internals of Firefox very well.
