### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/bookmarks-organizer#11]
A whitelist should be added to exclude bookmarks from future scans.

**Comment by jd666** [comment]
Please also allow whitelisting whole folder trees.
(Some session saver extensions save all open session tabs into specific bookmarks folders and BO will then complain about them being duplicates)

**Comment by cadeyrn** [comment]
A whitelist can be found in Bookmarks Organizer 3.0. An enhanced functionality will be in a future release. That's #96.
