### ISSUE TITLE
Adding a bookmark while performing a check leads to hang

### ISSUE THREAD

**Issue by gitflo** [cadeyrn/bookmarks-organizer#112]
Hi all,

I'm opening this ticket on addon version 3.1.0. I've observed that Bookmark Organizer will hang if a new bookmark is created while the addon is running a check (broken link check in my case).

The tricky aspect is that bookmarks are not only added manually, but may be added automatically after some time, when using a session manager's auto-save feature.

Kind regards
 Florian

**Comment by cadeyrn** [comment]
Thanks for the report. I have to check if I can reproduce and to investigate what can be done to prevent this issue (probably later this week).

**Comment by cadeyrn** [comment]
@gitflo Fixed in Bookmarks Organizer 4.0.
