### ISSUE TITLE
Bulk action removes tags

### ISSUE THREAD

**Issue by kaffeeringe** [cadeyrn/bookmarks-organizer#114]
I imported a lot of bookmarks from my old Scuttle installation. Scuttle uses tags to organize the bookmarks and they remain intact after the import. But many of the links now support https and when I run the repair function of the bookmarks organizer the tags get lost.

**Comment by cadeyrn** [comment]
Please see the notes:

> If you edit the URL of a bookmark or if you let Boomarks Organizer fix a redirect Firefox will “loose” the tags associated with the bookmark because bookmark tags are bound to the URL and not to the bookmark. The tags are not really lost, they are still associated with the old URL. This is neither a bug of Bookmarks Organizer nor of Firefox, it's how Firefox works. Please see [Bugzilla #1440988](https://bugzilla.mozilla.org/show_bug.cgi?id=1440988#c2) for context.

https://github.com/cadeyrn/bookmarks-organizer#note

There is no WebExtension API to read and write tags so there is nothing I can do.

**Comment by kaffeeringe** [comment]
Okay, I see. Is it possible to copy the tags while changing the URL?

**Comment by cadeyrn** [comment]
No. As I said: There is no WebExtension API to read and write tags. ;-)
