### ISSUE TITLE
confirm/deny modal by enter/esc

### ISSUE THREAD

**Issue by stonecrusher** [cadeyrn/bookmarks-organizer#116]
Just a UX enhancement:
When going through a long warning list by hand (fixing redirects), it's a nuisance to always click OK in the modal popping up.
Confirming that modal by pressing enter would be helpful (maybe just focus OK button by default).

Also, closing the modal / cancel by pressing ESC would be a good complement for that "shortcut" feature.

**Comment by cadeyrn** [comment]
Thanks for using Bookmarks Organizer.

Closing the dialogs by pressing ESC is already possible. Confirming by pressing enter is probably a good idea. I will consider this request for the next update.

**Comment by keunes** [comment]
alternatively, support for pressing `y` or `n` would also be great

**Comment by pie-faced** [comment]
I would like an option to toggle confirmation dialogs on/off. For me it would be much better on first run with over 200 duplicates to deal with to not have to reassure your app that I know what I am doing 200 plus times (every time I choose to delete a duplicate). Also I have scoured about:config and every file in my profile folder to find where BookmarksOrganizer stores its settings and have only found one setting through about:config in prefs.js which toggles Boolean, and no other settings seem to be there--or anywhere I can find. Where are your settings stored?

**Comment by cadeyrn** [comment]
> I would like an option to toggle confirmation dialogs on/off

Such an option is already implemented. You can find it in the add-on's settings.

> Where are your settings stored?

The settings of *all* WebExtensions are stored in the storage directory in your profile folder.

Please note that neither your request nor your question has anything to do with the feature request of this issue.

**Comment by cadeyrn** [comment]
This is already implemented.
