### ISSUE TITLE
Alle Doppelten Löschen

### ISSUE THREAD

**Issue by goldjunge91** [cadeyrn/bookmarks-organizer#117]
hi
eine möglichkeit alle doppelten bis auf eins auf einmal löschen

**Comment by cadeyrn** [comment]
Hallo und Danke für den Vorschlag.

Das ist ein Duplikat von #38.

Das ist nicht ganz trivial, weil die Frage natürlich ist, *welche* Lesezeichen nun gelöscht werden und welche behalten werden sollen und es auf diese Frage kein 'richtig' oder 'falsch' gibt. Das heißt, es müssen bestimmte Regeln vom Benutzer festgelegt werden können.
