### ISSUE TITLE
Bookmarks not being identified as such after making changes

### ISSUE THREAD

**Issue by achavez48** [cadeyrn/bookmarks-organizer#120]
Hello again,
It's being a while after I used the add-on, but now I remember a curious thing that happened after using it. After changing redirects like http->https and similar, although the bookmarks are there and changed when I go to the link the "Star" icon that should be indicating that I have that bookmark is not lit. So when I go to some bookmarks I only know that I have them after searching in the bookmarks bar. And if I bookmark it again, in the search it appears twice (apparently as a duplicate), the only difference is the title that changes which is the updated one, but the address is the same.

**Comment by cadeyrn** [comment]
@achavez48 Is this still an issue for you?
