### ISSUE TITLE
Bookmarks Viewer, Editor and Unpacker

### ISSUE THREAD

**Issue by hightower5** [cadeyrn/bookmarks-organizer#124]
I was looking for a plugin which can open and edit the bookmark backup files .jsonlz4.

It would be nice, if the bookmarks-organizer could handle these .jsonlz4 files.

**Comment by cadeyrn** [comment]
Hi,

thank you for your suggestion. Unfortunately this is out-of-scope for Bookmarks Organizer. Bookmarks Organizer does not operate with files at all, only with the WebExtension API for bookmarks. There are no plans to add support for importing backup files and do something with these.
