### ISSUE TITLE
Show containing folder of bookmark

### ISSUE THREAD

**Issue by fho4train** [cadeyrn/bookmarks-organizer#126]
The organization of bookmarks in Folders gets messy after many additions to many (nested) folders. Firefox can search for bookmarks but gives no direct indication of the containing folder. In order to improve the organization of the bookmarks by folder an option to show the containing folder(s) of bookmarks would be helpful.

**Comment by stevenvh17** [comment]
That one bugs me too. But it seems to me that it's an issue with the Firefox bookmarks management module, not the bookmarks-organizer add-on.
That said, bookmarks are probably the worst implemented feature of Firefox. Not only doesn't show you the containing folder, it will happily add a bookmark in a folder which already contains it. And a duplicate finder/remover should be built-in.

**Comment by sfMan** [comment]
That problem bothered me to and I created an issue. I figured out that problem comes with bookmark folder names (maybe bookmark names too, not sure). When it contains special characters used in path defining like / or # addon badly reads locations and adresses.

**Comment by cadeyrn** [comment]
The Bookmarks Organizer shows the containing folder since its first version.

**Comment by fho4abcd** [comment]
We may have a different idea where and how the containing folder is shown. What is meant in this ticket is that the drop-down to modify the show attributes doe NOT show that containing folder. See attached screenshot
![2023-01-08 10_18_23-Library](https://user-images.githubusercontent.com/64411779/211188850-61652375-5c92-4e1e-820a-8c7e5d048701.jpg)

**Comment by cadeyrn** [comment]
The add-on has nothing to do with the library at all.

**Comment by fho4abcd** [comment]
OK. So sorry. My fault. Found your add-on now.
