### ISSUE TITLE
Automatically fix http:// to https:// redirects

### ISSUE THREAD

**Issue by stevenvh17** [cadeyrn/bookmarks-organizer#127]
When checking broken bookmarks I have a lot of them where the only change is from http:// to https://, with the remainder of the URI/URL exactly the same. It would be nice to have an option to fix all of these automagically. Thanks

**Comment by cadeyrn** [comment]
Hi,

there is already a feature to fix all redirects ("warnings" in Bookmarks Organizer), not only HTTP->HTTPS. Is there an use case for fixing HTTP->HTTPS redirects but not all the other redirects?

**Comment by alexolog** [comment]
Some redirects are false positives, like adding a session token, redirecting to a login page when logged out, etc.  HTTP to HTTPS is a special case.

**Comment by 894-572** [comment]
> there is already a feature to fix all redirects ("warnings" in Bookmarks Organizer), not only HTTP->HTTPS. Is there an use case for fixing HTTP->HTTPS redirects but not all the other redirects?

@cadeyrn There absolutely is! Dozens of my bookmarks require logging in and redirect to some landing page when not, the addon would break all of the links if I'd correct all redirects. Also [the Firefox keyword search](https://support.mozilla.org/en-US/kb/Smart%20keywords) breaks for at least Wikipedia and srrdb.com.

I humbly ask you to implement this feature.

**Comment by 894-572** [comment]
Additional issues:

* On some forums I redirect to the last page of a thread by using the `page-99` URL string (or similar). This is removed by bookmarks-organizer.
* Deleted pages commonly redirect to the front page, "correcting" the links with the addon would cause you to loose all bookmarked pages, most of which have likely been backed up by [archive.org](http://archive.org/web/web.php).

**Comment by joberreiter** [comment]
> > Is there an use case for fixing HTTP->HTTPS redirects but not all the other redirects?
> 
> @cadeyrn There absolutely is! Dozens of my bookmarks require logging in and redirect to some landing page when not, the addon would break all of the links if I'd allow "correcting" all redirects. Also [the Firefox keyword search](https://support.mozilla.org/en-US/kb/Smart%20keywords) breaks for at least Wikipedia and srrdb.com.
> 
> I humbly ask you to implement this feature.

I copy that. I have also the same problem and wanted to have that feature implemented.

**Comment by joberreiter** [comment]
Just referencing #9.

**Comment by cadeyrn** [comment]
Closing as duplicate.
