### ISSUE TITLE
Make use of optional permissions

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/bookmarks-organizer#14]
Make use of optional permissions and don't ask for all permissions on install. It will require Firefox 55, so it cannot implement before 2017-08-08.

**Comment by yfdyh000** [comment]
What permissions should be fill in? I did not see a significant unnecessary application for permissions.

**Comment by cadeyrn** [comment]
At the moment I can't say which permissions should be optional and which not. The idea behind this ticket is the following:

WebExtension permissions are similar to Android permission so I expect similar user concerns: "why does it need so many permissions?"… It still has to be investigated if it makes sense to use optional permissions for this extension, maybe this ticket will be WONTFIXED. But it would be nice if the required permissions could be reduced to reduce the user concerns and don't ask for the permissions until they are really needed.

Example: we don't need the <all_urls> permission to check for duplicates or bookmarks without title. We only need it for the broken bookmark check. So it could make sense to request this permission on runtime once needed. On the other side the broken bookmark check is one of the main features and you could say it does not make much sense to use optional permissions for this.

This ticket is to think about it. :)

**Comment by cadeyrn** [comment]
I think all permissions of Bookmarks Organizer 2.0 should be treated as mandatory so this is a WONTFIX for now.

**Comment by irvnriir** [comment]
i though the Addon includes a manager/search . if it stays only for checking, then yeah, current permissions are required . but why would it not allow to search/{interact with} the list of bookmarks, without checking ?

**Comment by cadeyrn** [comment]
> access your data for all sites with Find no longer working bookmarks feature needs to be optional .

Finding broken bookmarks is the primary feature of Bookmarks Organizer. I think Bookmark Organizer is one of the best extensions for finding broken bookmarks, but for finding duplicates there are definitively better add-ons. So I don't think that anyone will install this extension only for the duplicates or missing bookmark names check, so almost all users of Bookmarks Organizers need this permission.

Anyway, host permissions will always be treated as optional with Manifest V3 (MV3) so that will change with #181.

> why would it not allow to search/{interact with} the list of bookmarks, without checking ?

It was never the primary focus for this extension, especially since Firefox already can show your bookmarks and has a search field. Sure, in a perfect world with endless time I would integrate every feature that makes sense for the organization of bookmarks. But that's not the reality, unfortunately.

**Comment by cadeyrn** [comment]
@irvnriir Bookmarks Organizer 4.0 will need the permission for accessing all website data only for the check for broken bookmarks, no longer for the other two modes. Therefore the permission is no longer needed to install Bookmarks Organizer. Instead the extension asks at runtime when you want to use the broken bookmarks check. Fixed by #181 and #190.

**Comment by irvnriir** [comment]
@cadeyrn im currently using Firefox 102.7 ESR , it says the extension requires never version, ill definitely try it when i can .
