### ISSUE TITLE
Japanese translation of "Bookmarks Organizer version 3.1.0"

### ISSUE THREAD

**Issue by Shitennouji** [cadeyrn/bookmarks-organizer#141]
> bookmarks-organizer/src/_locales/日本語/messages.json
> locales: 日本語（ja-JP）

{
  "action_delete_all_bookmarks_with_errors": {
    "message": "動作しないブックマークをすべて削除する"
  },
  "action_repair_all_redirects": {
    "message": "すべてのリダイレクトを修復する"
  },
  "bookmark_action_add_to_whitelist": {
    "message": "ホワイトリストに追加する"
  },
  "bookmark_action_edit": {
    "message": "編集する"
  },
  "bookmark_action_delete": {
    "message": "削除する"
  },
  "bookmark_action_repair_redirect": {
    "message": "リダイレクトを修復する"
  },
  "bookmark_confirmation_delete": {
    "message": "このブックマークを削除しても大丈夫ですか？この操作は元に戻すことができません。"
  },
  "bookmark_confirmation_delete_all_broken": {
    "message": "動作しないブックマークを、すべて削除しても大丈夫ですか？この操作は元に戻すことができません。"
  },
  "bookmark_confirmation_repair_all_redirects": {
    "message": "リダイレクトされたすべてのブックマークの URL を変更しますか？この操作は元に戻すことができません。"
  },
  "bookmark_confirmation_repair_redirect": {
    "message": "このブックマークの URL を変更してもよろしいですか？この操作は元に戻すことができません。"
  },
  "bookmark_confirmation_whitelist": {
    "message": "このブックマークを恒常的に無視しても大丈夫ですか？"
  },
  "bookmark_name": {
    "message": "（タイトル）名称"
  },
  "bookmark_no_name": {
    "message": "（タイトル）名称なし…"
  },
  "bookmark_path": {
    "message": "パス"
  },
  "bookmark_url": {
    "message": "URL"
  },
  "button_check_bookmarks": {
    "message": "ブックマークを検査 …"
  },
  "button_reset_whitelist": {
    "message": "ホワイトリストをリセット …"
  },
  "close_overlay": {
    "message": "閉じる"
  },
  "confirm_btn_cancel": {
    "message": "取り消す"
  },
  "confirm_btn_ok": {
    "message": "OK"
  },
  "edit_bookmark": {
    "message": "ブックマークを編集する"
  },
  "extension_description": {
    "message": "Bookmarks Organizer（ブックマーク支援機能）を使用すれば、ブックマークを簡単に整理することができます。Bookmarks Organizer は、動作しなくなったブックマーク、リダイレクト、重複などを検出します！"
  },
  "extension_name": {
    "message": "Bookmarks Organizer（ブックマーク支援機能）"
  },
  "filter_errors": {
    "message": "何かが間違っています"
  },
  "filter_warnings": {
    "message": "警告"
  },
  "greeting": {
    "message": "こんにちは！"
  },
  "intro_check": {
    "message": "ブックマークの検査では、選択したモード、ブックマークの数、インターネットの速度によっては数分かかる場合があります。動作しないブックマークの検査中は、ウェブサイトの読み込みが著しく遅くなることがありますのでご注意下さい。"
  },
  "mode_broken_bookmarks": {
    "message": "動作しないブックマーク"
  },
  "mode_duplicates": {
    "message": "重複"
  },
  "mode_empty_names": {
    "message": "ブックマーク名称の欠落"
  },
  "no_marked_bookmarks": {
    "message": "ブックマークは、全て問題ありません！"
  },
  "no_marked_bookmarks_title": {
    "message": "いいね！"
  },
  "omnibox_command_check_duplicates": {
    "message": "重複したものを探す"
  },
  "omnibox_command_check_empty_names": {
    "message": "（タイトル）名称のないブックマークを探す"
  },
  "omnibox_command_check_errors": {
    "message": "アクセス可能なブックマークは検索しない"
  },
  "omnibox_command_check_organizer": {
    "message": "Bookmarks Organizer を開く"
  },
  "omnibox_command_check_redirects": {
      "message": "リダイレクトするブックマークを探す"
  },
  "omnibox_default_description": {
    "message": "すべてのブックマークに、エラー、リダイレクト、重複がないかを検査 …"
  },
  "option_debug_mode": {
    "message": "デバッグ出力を有効にする"
  },
  "option_disable_confirmations": {
    "message": "確認メッセージを無効化する（非推奨）"
  },
  "save_bookmark": {
    "message": "保存する"
  },
  "search_label": {
    "message" : "名称や URL を入力し、結果を絞り込む…"
  },
  "some_marked_bookmarks": {
    "message": "ここを少し掃除した方が良さそうですね！"
  },
  "some_marked_bookmarks_title": {
    "message": "やあ！"
  },
  "start_message": {
    "message" : "ここから始めましょう…"
  },
  "status_checked": {
    "message" : "検査済み"
  },
  "status_errors": {
    "message" : "何かが間違っています"
  },
  "status_total": {
    "message" : "ブックマークの数"
  },
  "status_warnings": {
    "message" : "警告"
  },
  "whitelist_reset_confirmation_msg": {
    "message" : "本当に、ホワイトリストをリセットしたいのですか？"
  }
}

**Comment by cadeyrn** [comment]
A Japanese translation will be included in Bookmarks Organizer 4.0.0. Please check if everything is correctly translated once it's released (will happen within the next few days).
