### ISSUE TITLE
Bookmarks check

### ISSUE THREAD

**Issue by geoffaray** [cadeyrn/bookmarks-organizer#143]
I only want to check bookmarks in my bookmarks folder but Bookmarks Organizer is listing hundreds of bookmarks that aren't in there, some of them have been previously deleted. Can I specify what to check, or delete any bookmarks that aren't in my bookmarks folder without going through them one by one?

**Comment by cadeyrn** [comment]
> Bookmarks Organizer is listing hundreds of bookmarks that aren't in there, some of them have been previously deleted

This is technically not possible at all. Bookmarks Organizer gets the bookmarks from the bookmarks WebExtension API and if this API finds bookmarks then these bookmarks exist.

> Can I specify what to check, or delete any bookmarks that aren't in my bookmarks folder without going through them one by one?

It's planned but in the current version it's not possible.

**Comment by geoffaray** [comment]
Hello Soren,

Thanks for your quick reply. If I can’t see the so called deleted bookmarks in my bookmarks folders, where do I find them? I know some of them are really old.

Regards

Geoff

**Comment by cadeyrn** [comment]
There are several places where bookmarks could be located: The bookmarks menu, the bookmarks toolbar, the "other bookmarks" or a "mobile bookmarks" folder if you're using Sync. You can access all of these within the library of Firefox.

**Comment by geoffaray** [comment]
I’ve just had a look at Firefox/bookmarks/show all bookmarks. There are many duplicate Bookmarks Menu, Bookmarks Toolbar and Bookmarks folders with different bookmarks, including many that I deleted, some years ago.
I’ll remove the old duplicate folders, that should get rid of the old bookmarks. I had no idea they were all there.

Thanks for your help, much appreciated.
