### ISSUE TITLE
Make Firefox bookmarks very searchable

### ISSUE THREAD

**Issue by papidoyce** [cadeyrn/bookmarks-organizer#145]
I would like to see as new features the possibility to select and sort by up to 5 tags and keywords, then display the bookmarks in a list.
There should also be an easy way to search and replace tags or keywords that are spelled wrong or combined when they were not supposed to.

**Comment by cadeyrn** [comment]
Thanks for using Bookmarks Organizer.

There is no tags or keywords WebExtension API for bookmarks in Firefox so this request can't be implemented.
