### ISSUE TITLE
Bookmarks Organizer output is where? 

### ISSUE THREAD

**Issue by bmazak** [cadeyrn/bookmarks-organizer#146]
Bookmarks Organizer output is where?  I ran it and it was finding bad sites but explain what the add-on does with these. What should I expect it to do and how and where.

**Comment by cadeyrn** [comment]
Hi,

You can find screenshots on https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/.

**Comment by bmazak** [comment]
Typical answer, look for it. Well I don’t have time to look for it. The screen shots do not not answer the question.  What is done with a bad link? Deleted, Quarantined? How is the bookmark treated? DO you remove it? Put it somewhere, Mark it?  How does the bookmark file change after running scan for bad links, any None?  It is not clear what happens.

**Comment by cadeyrn** [comment]
> Typical answer, look for it. Well I don’t have time to look for it. The screen shots do not not answer the question. 

I don't have to answer at all if you react with disrespectful sentences like "typical answer". Your question was "output is where?" and the screenshots show the output. And yes, you should take the time to look at the screenshots and read the description of the add-on, especially the "features" section because it answers your other questions.

If you don't have the time to read the description then you really shouldn't use my or any other add-on. It's always important to read the developer's notes before installing an add-on. And honestly, asking these questions here on GitHub definitively took more time than reading the description so I don't buy the "I don’t have time" sentence.

**Comment by bmazak** [comment]
Well I’m sorry,  I mean the time it takes looking over and over again at the output and screen shots and goggles I did trying to find those answers.   Your screen shots display is very small and I really don’t see what you app does with a bookmark that has a bad link.  Why don’t you have someone else look at the description page and answer those question.  I appreciate the App so, thank You, I’m expecting rows and rows of displayed bad links in several folders.  The first time I ran it out of the 4063 bookmarks, last I looked, it said out of 400 80 were bad.  Then I went about my work and later I looked and it had the display right back where it was when I started last time with 0 processed and 0 errors. SO, I’m asking now is, is there a log somewhere that would show me what happened during that run that seems to have no output.  Here’s what I was expecting.

 

Somewhere on the list of functions: “A bad link in bookmark toolbar and folder **** and sub folder **** was fond and it was removed” no bad bookmark links that were reported during the run were removed I still have 4063 bookmarks.

**Comment by bmazak** [comment]
I keep reading this message from you and let me explain.  What I don’t have time for is looking for something wrong, not, reading the description.  I read it and looked at the pictures and now I see what the output is supposed to be for Broken Bookmarks but I’m not getting any.  All I see is a competition bar that goes  to what looks like the end but the counting of processed bookmarks and errors has stopped and the Icon in the middle of the page is still active.  It just sits there all day on a separate window.  I don’t think it likes doing other things while it working or something.  So I was hoping you could explain what it looks like when this function ends but no need.  I ran it this morning and the network was down so I saw it finish with all bookmarks marked as error.  Something wrong there, but I understand.

 

I apologize for the confusion.  A lot of developers are working hard to get little or no recognition for their work and support.  SO who needs a cranky old man like me, rite?   Again thanks for you work.  Here’s a little token of appreciation.

**Comment by marxenegls** [comment]
Where is the "Clean This Mess Up" button ?

i have the same issue - it sifted through 9000 found 3000 errors,  i suppose doubles, but it doesn't tell me how to remove them, on hover i see "edit" and "delete" tooltip, but that can't be right - i'm not going to go manually through 3000 doubles - what's the point in having a utility that's designed for the purpose, - 

I see no shortcuts, no CLI commands, no explanation of what is and what isn't -
a "green", "orange", and "red" tab - all dead but a fox that talks, when poked - wtf
"Hey!
Looks like we could clean up a little here!"

OK, what are you waiting for ? - clean up 

i typically use buku CLI to sort but the issue with that is when reimporting back into ff - i'd still have to clear out all the bookmarks first - i suppose,
and why isn't all this in ff itself ? - it already sorts from A>Z, dates  - it could also remove doubles,
 Jesus Christ version 85, 15yrs on and i'm still witching about bookmarks it still doubles - no more syncing is the only solution i could think of - smartphone doesn't need 5000+bookmarks - Google Maps + Duo is plenty

I'm not amused :(

**Comment by cadeyrn** [comment]
>  i suppose doubles

The answer depends on what you did. Either you checked for broken bookmarks or for duplicates. For duplicates there is no mass removal action in the current version. For broken bookmarks see the link in the first answer for screenshots showing the position of the mass removal link.
