### ISSUE TITLE
ver-3.1.0 Sub folder not working to  place on top

### ISSUE THREAD

**Issue by bmazak** [cadeyrn/bookmarks-organizer#152]
I just checked 1-28-21 it does not work for sub folders.  I have over 1000 bookmarks and use folders to organize my sites.

**Comment by achavez48** [comment]
I have more than 80k bookmarks and placed in several sub folders, and it does look through them.

**Comment by bmazak** [comment]
Sorry I mean that new bookmarks are not going to the beginning in sub folders, they are stored at the end.  Using bookmarks Organizer.
