### ISSUE TITLE
Broken Bookmarks -> Tags / Keywords...

### ISSUE THREAD

**Issue by ChristianGaede** [cadeyrn/bookmarks-organizer#154]
...werden gelöscht, wenn man "correct redirect" ausführt.

MfG

**Comment by cadeyrn** [comment]
Es wird nichts gelöscht, es ist viel mehr ein Missverständnis über die Funktionsweie von Tags in Firefox. Siehe README:

> If you edit the URL of a bookmark or if you let Boomarks Organizer fix a redirect Firefox will “loose” the tags associated with the bookmark because bookmark tags are bound to the URL and not to the bookmark. The tags are not really lost, they are still associated with the old URL. This is neither a bug of Bookmarks Organizer nor of Firefox, it's how Firefox works. Please see [Bugzilla #1440988](https://bugzilla.mozilla.org/show_bug.cgi?id=1440988#c2) for context.
