### ISSUE TITLE
Let users disable (forever/in this session) delete confirmation prompt

### ISSUE THREAD

**Issue by pstein** [cadeyrn/bookmarks-organizer#164]
When I delete a broken shortcut in BO then always a confirmation prompt appears "Do you really want to delete this bookmark?".

This could be annoying when I delete multiple bookmarks.

I suggest to introduce an option/checkbox to ask for confirmation again (at least until the end of the current BO session).

Thank you

**Comment by cadeyrn** [comment]
Hi,

such an option already exists in the add-on's settings.

**Comment by pstein** [comment]
Thank you
