### ISSUE TITLE
Translations for Bookmarks Organizer 4.0

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/bookmarks-organizer#193]
For the upcoming release of Bookmarks Organizer 4.0 three new strings were added. I will mention the previous translators. Please let me know if you don't want to contribute further. If you need a bit time: No problem! I can fall back to English for these few strings in the meantime and release updates for updated translations as they arrive. :)

```
"permission_description": {
    "message": "In order for the check for broken bookmarks to work, it is technically necessary to grant permission to access the data for all websites."
},
"permission_grant_button": {
    "message": "Grant permission"
},
"permission_needed": {
    "message": "Permission required"
},
```

@vasimi for Czech
@TarekJor for Spanish
@MichelePezza for Italian
@dlwe for Japanese
@coffeemesh for Turkish
@yfdyh000 for Chinese (Simplified)
@zhtw2013 for Chinese (Traditional)

Thank you!

**Comment by coffeemesh** [comment]
I have delegated this task (updating the Turkish translation) to the user @r0tbra1n since I think it is a very fitting oppurtunity for beginners to tackle and get familiar with some of the workflows on Github or open source projects in general.
Also his turkish is marginally better than mine.

**Comment by cadeyrn** [comment]
Thank you for delegating. :)
