### ISSUE TITLE
Bug "BO v4.0.0 needs an updates version of Firefox" - when using PortableApps Firefox?

### ISSUE THREAD

**Issue by pstein** [cadeyrn/bookmarks-organizer#200]
I am running the newest 64bin  (PortableApps! ) Firefox v108.0.2 on Windows10 from
https://portableapps.com/de/apps/internet/firefox_portable

When I go to the Bookmark Organizer download page 

https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/

I was informed that:

You need an updated version of Firefox for this extension

Hmm, whats wrong? I ALREADY HAVE the newest version

I cannot believe that using portableapps firefox is the problem.
since I use dozends of other AddOns without problem

So it must be a bug in BO v4.0.0

Can you check and fix the problem?

**Comment by cadeyrn** [comment]
Bookmarks Organizer 4.0 requires Firefox 109 or higher. Firefox 109 will be released on Tuesday.
