### ISSUE TITLE
False errors on version 4.0.0

### ISSUE THREAD

**Issue by sleek22** [cadeyrn/bookmarks-organizer#201]
After updating to Firefox version 109 and updating to Bookmarks Organizer 4.0.0, a run on my roughly 9,000 bookmarks gives about 500 errors. (These are the errors with the red badge. The Warnings on the yellow badge seem to be working fine.)

While some of these errors are real, the majority of the sites are not and open easily and quickly when clicked from within the add-on.

After some checking, it appears that it's flagging bookmarks with the prefix "http://" as errors. I checked my bookmarks folder with a "http://" search and I have about 400 of these in my bookmarks, so I think that's the problem here.

I should note that some of these sites showed up with the redirects from "http://" to "https://" on the Warning badge and these I corrected before running the test. It seems to me the problem is that it gives a warning if it finds a redirect to a "https://" version, otherwise it throws an error on the Red badge for all "http://" links with no redirect, even if they work correctly otherwise.

**Comment by cadeyrn** [comment]
Please give me the exact URLs of the bookmarks with a wrong result.

To reproduce the issue I also need a few more information:

Do you use the HTTPS only mode? Are you in private mode? How does your tracking protection settings look like? Are other add-ons enabled, if yes, which one?

**Comment by Illegal-Services** [comment]
I'm also experiencing that problem using the new version.

290 errors on 5570 bookmarks.

I have ~514 items starting from http://

I do not have "HTTPS ONLY" enabled (it's turned off).

**Comment by sleek22** [comment]
First, sorry for my slow response.

I have about 80 add-ons. I ran a test on about 9,000 bookmarks and got 499 errors. Then I disabled all add-ons except for Bookmarks Organizer, restarted Firefox, and then ran the test again and got 495 errors, so I think that excludes other add-ons.

My settings are:

-"Don't enable HTTPS-Only Mode" checked on
-Under Tracking Protection, the Standard one is greyed out so I believe I'm on Enhanced Tracking Protection. I checked the list of websites there and there only about 12 or so and they are not the ones I'll be listing later as having errors.
-As for "private mode", I don't know what that means. I just run the standard Firefox download without containers or anything.

As for the sites that always throw an error (red badge), here are three of them.

[http://bilbo.economicoutlook.net/blog/?p=48895](url)

[http://www.winterspeak.com/2009/01/rewording-keynesianism.html](url)

[http://www.mprinstitute.org/vaclav/Barbour.htm](url)

**Comment by cadeyrn** [comment]
Thanks for reporting and the examples. I did I found the cause. I will release an update later today (but it can take a few days until it's approved by Mozilla).

**Comment by cadeyrn** [comment]
@sleek22 @Illegal-Services Bookmarks Organizer 4.0.1 with a fix for this issue is now available on addons.mozilla.org.

**Comment by sleek22** [comment]
I updated Bookmarks Organizer to 4.0.1 this morning and ran a test, and now I am getting 102 errors on roughly 9,000 bookmarks. I checked about 10 bookmarks and 9 were throwing 404 errors or Firefox saying there was something wrong with that site's security certificate, so it's working properly now.

Thank you for making this add-on and for fixing the problem.
