### ISSUE TITLE
[FEATURE REQUEST] - Add keybind to whitelist prompt UI

### ISSUE THREAD

**Issue by Illegal-Services** [cadeyrn/bookmarks-organizer#205]
**Describe the solution you'd like**
I wish when Bookmarks  Organizer ask you if you are sure to whitelist an item, first maybe a setting to disable that prompt, and also a feature that keybind {ENTER} keyboard key to accept, and maybe {del} and {delete} to cancel.

All of that because it takes really a lot of time to answer manually with the mouse to this prompt when you have a lot of bookmarks to whitelist.

**Additional context**
![firefox_2023-02-02_16-42](https://user-images.githubusercontent.com/62464560/216370946-adc44993-6ceb-4fa3-8481-f18415365495.png)

**Comment by cadeyrn** [comment]
> first maybe a setting to disable that prompt

There is already an option in the add-on's setting for disabling the prompt.

> and also a feature that keybind {ENTER} keyboard key to accept, and maybe {del} and {delete} to cancel.

You can use ESC to cancel the dialog. Using Enter for the OK button makes sense and is easy doable. Will be done in the next feature update.

**Comment by Illegal-Services** [comment]
perfect, thanks a lot!

**Comment by cadeyrn** [comment]
6028d20ad65e0078909e37a3a16b4e475f8b84ed

**Comment by cadeyrn** [comment]
@Illegal-Services Bookmarks Organizer 4.1.0 has been released and it includes your requested change.
