### ISSUE TITLE
Addon freeze

### ISSUE THREAD

**Issue by kpanos777** [cadeyrn/bookmarks-organizer#216]
Those links (Connection timed out) freezes the addon and cannot complete checking bookmarks :
https://www.autotecparts.gr/
https://www.navimania.gr/

- Firefox Nightly 117.0a1 (2023-07-29) (64-bit)
- Bookmarks Organizer version 4.0.1

**Comment by cadeyrn** [comment]
I can't reproduce the issue. I see neither a connection time out nor a freeze of the add-on.
