### ISSUE TITLE
Estimated time for scan needs to be noted in beginning

### ISSUE THREAD

**Issue by Ecofoot** [cadeyrn/bookmarks-organizer#228]
The SCAN takes a long time! An estimate of the amount of time needed for full scan should be conveyed in beginning. Perhaps scan should do "chunks" of browser tree if many bookmarks then save these "chunks" to separate files with folder structure.

**Comment by cadeyrn** [comment]
It is not possible at all to estimate the time before the scan since it depends on multiple factors, including your network stability and available bandwidth, the response time from the servers, whether one or two requests have to be made per bookmark, and probably more.

**Comment by Illegal-Services** [comment]
Well it is possible if you only look backward. You see how much progressed so far, and estimate this percentage with the completed one.
Of course that makes it possible to do it but, it won't be an absolutely accurate result.

**Comment by cadeyrn** [comment]
A serious estimation is not really possible. You can have the best internet speed and stability when you start the check, and after an undefined amount of checked bookmarks it suddenly becomes very unreliable. Also, it depends on the bookmarked pages whether one or two checks per bookmark are needed. And if you have many bookmarks for one domain, it's also possible that the server of this website will block or throttle you after x requests. So the progress has really no meaning for the remaining bookmarks.

**Comment by Illegal-Services** [comment]
I completely agree with that
