### ISSUE TITLE
Progress bar stuck in the middle / end during the scan

### ISSUE THREAD

**Issue by Illegal-Services** [cadeyrn/bookmarks-organizer#229]
**Describe the bug**
The progress bar stuck in the middle / end during the scan in all my firefox profiles, even after reinstalling Bookmarks Organizer
Am I the only one ?
Also it seems like when dealing with less bookmarks it works fine??
I didn't had this problem before 1 week or something

**To Reproduce**
idk man it's a weird issue from my side I believe?

**Expected behavior**
The progress bar to complete and show the different Warnings and Errors just like usual.

**Screenshots**
![image](https://github.com/cadeyrn/bookmarks-organizer/assets/62464560/d8c869df-bbe5-4886-912d-4b5679850a3e)

**Version information:**
- Firefox version: 117.0 (64-bit)
- Bookmarks Organizer version 4.1.0

**Additional context**
nul

**Comment by Illegal-Services** [comment]
oh man I just noticed that launching the same thing on a VM works, I beleive my Firefox browser is the problem, I'll try reinstalling it, I guess thatwill works to fix it

**Comment by Illegal-Services** [comment]
Also, scanning using the github main branch source code, in about:debugging, works fine (there are a bunch of errors in the console but it works)

**Comment by Illegal-Services** [comment]
so I found another way to fix, it's by scanning with about:debugging console opened, then it works, if it's not opened, when the bar will stuck itself the background script will stop

**Comment by Illegal-Services** [comment]
I believe opening the console force the background script to stay alive?

**Comment by Illegal-Services** [comment]
the background script exactly shut down after 30 seconds it seems

**Comment by Illegal-Services** [comment]
https://github.com/cadeyrn/bookmarks-organizer/assets/62464560/3c33f023-33a2-4262-8427-37bb4965d275

**Comment by Illegal-Services** [comment]
I'm thinking it's probably something wrong with my browser, and not with Bookmarks Organizer but what the hell is that and why and how lol

**Comment by Illegal-Services** [comment]
or it's a bug introduced in a newest version of Firefox (i'm using latest atm)

**Comment by cadeyrn** [comment]
If it always happens after exactly 30 seconds, it sounds like a bug in Firefox or something the add-on's code have to handle better. Did this already happen with the same version of Bookmarks Organizer and previous versions of Firefox?

**Comment by Illegal-Services** [comment]
omg yes that's the issue, I updated Firefox from my VM to latest version, (it was working on v116.something and now on v117 it breaks.

**Comment by Illegal-Services** [comment]
So that's either an issue from Firefox OR a new feature that we devs have to implement to keep the background pages alive.

**Comment by Illegal-Services** [comment]
"Did this already happen with the same version of Bookmarks Organizer and previous versions of Firefox?"
> No, but I guess I Figured the bug now, I'm kindda lazy to hit Firefox github pages, I'll see the changelog of firefox v117 now

**Comment by Illegal-Services** [comment]
So I read that changelog, nothing seems to appear about background scripts, tho they did enhance the console.
https://www.mozilla.org/en-US/firefox/117.0/releasenotes/
and it's kindda related because I remember, opening the console makes it working, cuz it forces the background script to be alive.

**Comment by Illegal-Services** [comment]
![firefox_2023-09-03_13-36](https://github.com/cadeyrn/bookmarks-organizer/assets/62464560/3ee3ef3d-635e-47e4-b46d-a8a0f7363a19)

```
13:35:36.870 Background event page was not terminated on idle because a DevTools toolbox is attached to the extension. view-source:moz-extension://17aa0c3f-5a07-4450-a1ed-5cb20c0775b1/_generated_background_page.html
```

mhmmm interesting, in the console I see Firefox tried to close it but cuz of console it didn't.

**Comment by cadeyrn** [comment]
I can confirm that Firefox stops the background script after 30 seconds in Firefox 117, but not in Firefox 116.0.3. I'll investigate.

**Comment by Illegal-Services** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/117

here they didn't mention anything about Background scripts, it really seems like an Firefox new issue tbh

**Comment by cadeyrn** [comment]
Yes, I guess it's a bug. I'll try to find the culprit with the help of mozregression (https://mozilla.github.io/mozregression/)

**Comment by cadeyrn** [comment]
Caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1830767. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1851373

**Comment by Illegal-Services** [comment]
your welcome ^-^

**Comment by Illegal-Services** [comment]
![firefox_2023-09-04_07-04](https://github.com/cadeyrn/bookmarks-organizer/assets/62464560/83acf601-5f42-49c8-913a-e86bc8b902e2)

i found interesting to note that I'm creating a web extension on my side, and I'm not even using background.js right now (it's a moduled type popup.js, it does not call the background.js at all (it's included in the manifest.json but the background.js file is empty right now), and I still manage to have the same problem than if I was using a background.js lmfao

**Comment by Illegal-Services** [comment]
I'm gonna try to remove completely the background.js from my manifest and see if the bug still occurs lol

**Comment by Illegal-Services** [comment]
well yeah that worked, no more warning message

**Comment by Illegal-Services** [comment]
oh so the popup.js even with this error message and the dev console closed, it still finishes to complete, basically the only thing it does is close the empty background script page, tbh I don't even see a reason for it to run since that background.js file is well.. literally empty

**Comment by Illegal-Services** [comment]
cringe

**Comment by cadeyrn** [comment]
@Illegal-Services Does the attached version work for you? Can can test it via about:debugging (it's not signed).

**Comment by cadeyrn** [comment]
@Illegal-Services Does the attached version work for you? Can can test it via about:debugging (it's not signed).

[bookmarks_organizer-4.1.1b1.zip](https://github.com/cadeyrn/bookmarks-organizer/files/12516885/bookmarks_organizer-4.1.1b1.zip)

**Comment by Illegal-Services** [comment]
@cadeyrn Hello, that version indeed passed my tests, yes.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 4.1.1 has been released on addons.mozilla.org now.
