### ISSUE TITLE
Bookmark Checker gets stuck on last bookmark

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/bookmarks-organizer#23]
from user feedback:

"Sadly I haven't really been able to get much use from the add-on, as the broken bookmark checker always gets stuck on the last bookmark. From a glance at the console output it's possible that it could be due to a basic auth prompt, but I'm not sure and would happily help to find out."

**Comment by freaktechnik** [comment]
I've since manually cleaned up my bookmarks and thus managed to remove the problematic site. Sadly I do not know why it would get stuck. I would expect fetch() or whatever you're using to be failing at least after a network timeout, so I really don't see why it would just get stuck.

I guess you could at least improve how the extension handles the manager being closed while an operation is running and then re-opening it - I always had to disable and re-enable the extension to run any other action afterward, since this action probably was still around, but the newly opened version of the tab didn't know about it?

**Comment by cadeyrn** [comment]
Thank you for the fast reply!

Do you want to contribute your suggested improvement? :) Then I could focus on other improvements. ;)

**Comment by freaktechnik** [comment]
I should currently first finalize the port of one of my extensions before reading into new code bases.

**Comment by Gitoffthelawn** [comment]
@freaktechnik What was special about the bookmark that made it get stuck?

I'm experiencing the same thing, but I have no idea which bookmark is causing the issue.

**Comment by freaktechnik** [comment]
> @freaktechnik What was special about the bookmark that made it get stuck?
I sadly do not know either.

**Comment by grahamperrin** [comment]
> … stuck on last bookmark

Is that inferred when, for example: 

- the number of checks equals the number of bookmarks; **and**
- there's an error?

**Comment by Sopor-** [comment]
Mine will get stuck here:
```
Number of bookmarks
1520
Checked
1518
Warnings
600
Errors
75
```

**Comment by XhmikosR** [comment]
Is there any way to figure out which bookmark is causing the hang issue? I'm hitting this but I have no indication which one is causing this.

**Comment by Sopor-** [comment]
I should recommend to change extension to [404-bookmark](https://addons.mozilla.org/en-US/firefox/addon/404-bookmarks/)

**Comment by cadeyrn** [comment]
will be fixed in this branch:
https://github.com/cadeyrn/bookmarks-organizer/commits/abort-fetch

Unfortunately there is a bug in Firefox causing Firefox to crash:
https://bugzilla.mozilla.org/show_bug.cgi?id=1440941

**Comment by Gitoffthelawn** [comment]
Have you tried experimenting with the length of the timeout in:

`setTimeout(() => controller.abort(), 3000);`

**Comment by cadeyrn** [comment]
Yes. With a longer timeout Firefox crashes a few seconds later, but as long as Firefox crashes it's not good enough.

**Comment by Gitoffthelawn** [comment]
What about a shorter timeout?

**Comment by cadeyrn** [comment]
changing the timeout does not prevent the crash. And 3 seconds is already short. With a too short timeout the number of false positives will grow.

**Comment by cadeyrn** [comment]
Mozilla fixed the crash for Firefox 60 (I don't know yet if it will also be fixed for Firefox 59 or not) so I can continue to experiment this week.

**Comment by Gitoffthelawn** [comment]
Glad to see how fast Mozilla issued a patch.

@cadeyrn Do you have an understanding as to what is unique about certain bookmarks that cause the extension to fail when it encounters them?

**Comment by Gitoffthelawn** [comment]
Sounds good.  Perhaps allow the user to adjust the timeout duration.

**Comment by XhmikosR** [comment]
Awesome, thanks!

**Comment by 4ut0-M-4t** [comment]
Unfortunately v3.0.1 keeps getting stuck (Firefox 65).

**Comment by cadeyrn** [comment]
Please open a new ticket and provide information to reproduce if you have issues.

**Comment by 4ut0-M-4t** [comment]
May I ask why? I believe it's the very same issue. 
And I wonder what kind of additional information you require? Web Console log? I ask this because I have more than 2.5k bookmarks, thus the scanning process is time-consuming and you should not expect me to repeat it more than a couple of times in case you wanted to make sure the issue is reproducible under certain conditions.

**Comment by cadeyrn** [comment]
> May I ask why? I believe it's the very same issue.

Because this ticket is already closed. Whatever the cause in your case is, it's a different issue than the issues which has been fixed in the past.

> And I wonder what kind of additional information you require?

Since your report is the only report and I can't reproduce the issue a backup of your bookmarks would be the most helpful. I can only fix what I can reproduce.

**Comment by 4ut0-M-4t** [comment]
> Whatever the cause in your case is, it's a different issue

I take your point.
As to sending you a backup archive of all my bookmarks, I'm afraid it's not a feasible idea ATM. I'd have to purge it of all the private content first and then give it another go. It may take some time. 
Just keep my poor report in mind, please.
