### ISSUE TITLE
Don't ask me if I'm sure.

### ISSUE THREAD

**Issue by arkdae** [cadeyrn/bookmarks-organizer#232]
I have over 1,000 warning and over 400 errors. I don't want to just accept all changes, but would like to go through them one-by-one.

But clicking "correct redirect" asks me if I am sure that I want to make that change every single time. Please stop. I've already backed up my entire Firefox profile. Yes, I'm sure.

**Comment by cadeyrn** [comment]
You can disable the confirmation messages in the preferences of Bookmarks Organizer.

<img width="804" alt="Bildschirmfoto 2023-09-10 um 07 34 28" src="https://github.com/cadeyrn/bookmarks-organizer/assets/1100614/57726fce-38ab-4694-9ae4-165651494cba">

<img width="575" alt="Bildschirmfoto 2023-09-10 um 07 34 57" src="https://github.com/cadeyrn/bookmarks-organizer/assets/1100614/8cb9d13f-b8b3-443c-806f-2a4b9347ef4a">

**Comment by arkdae** [comment]
There's preferences?! Huzzah! I was looking all around the Bookmarks Organizer GUI itself. I didn't think to look there.
