### ISSUE TITLE
Fix link on mozilla addon page to issues

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/bookmarks-organizer#245]
**Describe the bug**
Link to issues isn't working on Mozilla addon page

https://outgoing.prod.mozaws.net/v1/03f1392112aab18a403eadb60882a6aee0c82b7855be518edb2072468833dd8a/https%3A//github.com/cadeyrn/bookmarks-organizer/issues

**To Reproduce**
1. Go to mozilla addon page
2. Click on link for issues
3. See error

**Expected behavior**
link should work

**Screenshots**
n/a

**Version information:**
- Firefox version: 127.0
- Bookmarks Organizer version: 4.0.2

**Additional context**
n/a

**Comment by cadeyrn** [comment]
I guess it was a temporary issue on the Mozilla side, as the link changed and prod.outgoing.prod.webservices.mozgcp.net is now used instead of outgoing.prod.mozaws.net. For me, clicking the link on addons.mozilla.org works.
