### ISSUE TITLE
Bulk fix for all redirects http to https

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/bookmarks-organizer#246]
**Is your feature request related to a problem? Please describe.**
Some collections can have a lot of old bookmarks using http.

**Describe the solution you'd like**
Offer a bulk fix for all redirects http to https where the only difference is the adding of an `s` in `http://`, optionally also accepting adding or removing trailing `/`.

**Additional context**
This would save the user a lot of time fixing the redirects.

**Comment by cadeyrn** [comment]
Duplicate of #9.
