### ISSUE TITLE
Links falsely detected as broken.

### ISSUE THREAD

**Issue by rscholer** [cadeyrn/bookmarks-organizer#36]
I've got 2 bookmarks that are always detected as broken, although the URLs are accessible.
This problem first occurred after the update to Bookmark Organizer 1.3.0.

The relevant debug information:
```
 {
    "bookmark": {
      "id": "D2zuHRJbKXiJ",
      "parentId": "dFAv3XE2qmPY",
      "title": "Online regex tester and debugger",
      "url": "https://regex101.com/",
      "status": 404
    },
    "method": "HEAD",
    "cause": "server-response",
    "response": {
      "url": "https://regex101.com/",
      "redirected": false,
      "status": 404
    }
  }
```
```
 {
    "bookmark": {
      "id": "odolJCrc9izD",
      "parentId": "JK5TPRGCuf1L",
      "title": "FanficAuthors.net",
      "url": "https://www.fanficauthors.net/",
      "status": 404
    },
    "method": "HEAD",
    "cause": "server-response",
    "response": {
      "url": "https://www.fanficauthors.net/",
      "redirected": false,
      "status": 404
    }
  }
```

**Comment by yfdyh000** [comment]
`curl --head https://regex101.com/` & `curl --head https://www.fanficauthors.net/` says: HTTP/1.1 404 Not Found. Server problem.
Provide an (Global / Recheck for items) option for use GET instead of HEAD? or any better ideas?

**Comment by rscholer** [comment]
> Provide an (Global / Recheck for items) option for use GET instead of HEAD?

It should already fall back to GET if HEAD fails, according to the changelog.

**Comment by yfdyh000** [comment]
But the HEAD get a successful but incorrect results. My idea is provide an action to allow user recheck for broken items using GET requests.
Or, blacklist for these sites? It may be a big project for reporting and maintenance.

**Comment by rscholer** [comment]
> But the HEAD get a successful but incorrect results.
Ok. I misunderstood the changelog then.

> My idea is provide an action to allow user recheck for broken items using GET requests.
The option and a blacklist would be perfect.

Additionally, do you think it would help to report this problem to the respective webmasters? Or is this false result of HEAD a common security feature?

**Comment by yfdyh000** [comment]
I think it is a mistake and should be reported to the webmaster, but I don't know whether it's universal and difficult to fix.

**Comment by cadeyrn** [comment]
Thank you for the report! I see two options:

1. revert the change and always do GET requests
2. always make a GET request if the status of the HEAD check is not "BOOKMARK OK"

My original plan was to implement option 2 but I thought I could avoid the second request under certain circumstances. I was wrong. It seems that a few websites shows a regular 404 page for HEAD requests, so I have always to do the second request if the status of the first check is not "BOOKMARK OK"…

It will be fixed in the next release.

**Comment by cadeyrn** [comment]
I commited a bugfix a few moments ago, it will be part of the next release and should be available soon.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 2.0 has been released:
https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/
