### ISSUE TITLE
(Suggestion) Add reload favicons feature.

### ISSUE THREAD

**Issue by happysurf** [cadeyrn/bookmarks-organizer#37]
Sometimes some web site (also after sync) appear without favicon, will be great have this feature for a complete and perfect bookmarks organizer.
Thanks.

**Comment by cadeyrn** [comment]
Thank you for your suggestion. Unfortunately I don't think it's possible because AFAIK there is no API for favicons. Maybe it will be possible in the future but at the moment I don't see a way. If you know a solution please let me know.

**Comment by happysurf** [comment]
You are right, also on Chrome Store not exist an extension for that.
Hopefully in the future.
Thanks.

**Comment by cadeyrn** [comment]
I will reopen the ticket once it will be possible. Thank you again for the suggestion.

**Comment by davidhedlund** [comment]
@cadeyrn It is possible now, see [Checkmarks](https://addons.mozilla.org/en-US/firefox/addon/checkmarks-web-ext/).
