### ISSUE TITLE
High memory and processor use without selecting any activity

### ISSUE THREAD

**Issue by HubJ** [cadeyrn/bookmarks-organizer#40]
This problem occurs in FF 52.2.1, running on Windows 7 SP1 (64-bit), installed on a Dell XPS410, with an Intel Core 2 Duo processor and 4 GB RAM.

As soon as the program's icon is clicked, and a new tab opens, FF jumps to 55 - 60 % CPU usage, although it was sitting idle the moment before. This happens before any selection is made from the choices in "Start Here." The high CPU utilization continues as long as the tab remains open, I'm only able to stop it by closing the tab.

Although the three lights in the middle of the interface page light in sequence as though something was happening, no numbers appear on any of the labels at the top of the GUI window to indicate that any bookmarks are being checked. 

Over the course of 15 minutes, FF memory usage rises from about 1 GB when opened with 462 tabs, to 2.58 GB.

**Comment by cadeyrn** [comment]
I can't reproduce the the issue on any of my testing systems and never got a similar reports. The add-on's interface is a simple HTML page with JavaScript, there is nothing special and no reason for such a huge memory increase. You could copy the content of about:memory in your next answer but I doubt that it will show a problem with this add-on.

**Comment by cadeyrn** [comment]
closed because lack of response. It can be reopened if there are any actionable working items.
