### ISSUE TITLE
Issues with sankakucomplex and rocketnews

### ISSUE THREAD

**Issue by rayman89** [cadeyrn/bookmarks-organizer#44]
All bookmarks I had from this sites http://en.rocketnews24.com/ http://www.sankakucomplex.com/ (NSFW) that were not the homepage appeared as broken even though there was no problem with them.

**Comment by cadeyrn** [comment]
I can't reproduce. Both URLs works for me. Please tell me the exact bookmark URLs if these are not the exact URLs.

**Comment by rayman89** [comment]
http://www.sankakucomplex.com/2014/12/04/monster-hunter-mezeporuta-kaitaku-ki-pv-revealed/
http://en.rocketnews24.com/2014/08/20/magazine-survey-picks-japans-10-best-towns-to-live-in/
http://en.rocketnews24.com/2015/06/16/japans-30-best-travel-destinations-as-chosen-by-overseas-visitors-2/
http://en.rocketnews24.com/2015/02/06/eat-your-beans-the-doubly-delicious-way-with-this-mushiyaki-edamame-recipe-%e3%80%90rocketkitchen%e3%80%91/

**Comment by cadeyrn** [comment]
I can't reproduce. Maybe it's fixed on their site.
