### ISSUE TITLE
Explain errors

### ISSUE THREAD

**Issue by grahamperrin** [cadeyrn/bookmarks-organizer#46]
For example: 

![2017-08-07 20 46 23](https://user-images.githubusercontent.com/192271/29043082-88c9cac2-7bb1-11e7-993e-51f8ea1cbf3c.png)

I aimed to click on the red alert. 

## Enhancement request

Please, can you make the red alert a button, that lists any error when clicked?

Thanks

**Comment by cadeyrn** [comment]
You executed the check for duplicates. The UI shows the affected URL and below the URL the two affected bookmarks with the same URL. I don't see how it can be useful to make the red circle a button.

The UI is not the best of the world, that's correct. But for the moment this ticket is a WONTFIX until a resdesign of the UI will happen. There are no concrete plans at the moment.

**Comment by grahamperrin** [comment]
@cadeyrn you're right! Sorry. Clearly I wasn't thinking straight when I raised this issue. I was probably mentally stuck thinking about issue 41, something like that.
