### ISSUE TITLE
Hangs on duplicates

### ISSUE THREAD

**Issue by jimcuk** [cadeyrn/bookmarks-organizer#48]
add on hangs when processing duplicates

**Comment by JustMyGithub** [comment]
When I search for duplicates, the "progress"-animation does not stop and I cannot delete one of the first 3 or 4 duplicates. Is that the problem you are talking about?!

**Comment by Jan02** [comment]
happens to me too: https://gfycat.com/PoorCorruptAtlasmoth

**Comment by bunnybooboo** [comment]
So this issue is actually that the icon `images/icon.svg` and its lower animated spinner/bounce icons give the impression that the task is still running, even though it's finished. Just tested in Firefox 57 and Firefox Nightly 59 and experienced this perceived "hang".

**Comment by bunnybooboo** [comment]
In fact this is a duplicate of #41

**Comment by cadeyrn** [comment]
Thanks for reporting. Will be fixed in Bookmarks Organizer 2.0.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 2.0 has been released:
https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/

If you like it please let a positive review there. ;-)
