### ISSUE TITLE
Conflict with some legacy addons

### ISSUE THREAD

**Issue by fireattack** [cadeyrn/bookmarks-organizer#49]
Fx Version: 56.0b3 (64-bit)

Repro: 

1. install bookmark organizer and this one https://addons.mozilla.org/en-US/firefox/addon/pagesaver/
2. Open bookmark organizer UI

What happened: it never finishes loading the bookmarks. Errors in browser console:

```
Attempt to create privileged extension parent from incorrect child process  ExtensionParent.jsm:646
	createProxyContext resource://gre/modules/ExtensionParent.jsm:646:15
	receiveMessage resource://gre/modules/ExtensionParent.jsm:598:11
Error: Could not establish connection. Receiving end does not exist.  undefined
```

This add-on is not the only one have this problem. So far I found a batch of them, such as [xthunder](https://addons.mozilla.org/en-US/firefox/addon/xthunder/) etc.

I suspect all the non-e10s compatible legacy addons will cause this. 

Also this is a regression, I always have those conflict addons installed, but bookmark organizers only stops to work recently.

**Comment by cadeyrn** [comment]
Thank you for the report. That's strange. But since Firefox 57 only supports WebExtensions and Firefox Nightly is already on version 57 I won't fix issues with legacy add-ons because the time will solve this problem.

Or are there similar issues with WebExtensions?

**Comment by fireattack** [comment]
This bug seems to be gone as now (Fx 56.0, BO 1.3.0).

**Comment by cadeyrn** [comment]
Thank you for letting me know!
