### ISSUE TITLE
有的書籤沒有路徑（some bookmarks no path）

### ISSUE THREAD

**Issue by cc85** [cadeyrn/bookmarks-organizer#56]
有的書籤沒有路徑（some bookmarks no path）
圖（限時72小時）： https://uploadpie.com/za78za

我找可以整理出重複書籤的應用程式已有段時間了，感謝你開發此附加元件！

**Comment by cadeyrn** [comment]
The link has expired. Is this still a problem and if so, can you please attach a new screenshot?
Also I don't know what these characters mean because I only can speak German and English.

**Comment by cadeyrn** [comment]
Please open a new issue if there is still an issue with the upcoming release of Bookmarks Organizer 2.0.
