### ISSUE TITLE
Reports some URLs as broken when they are not

### ISSUE THREAD

**Issue by Gitoffthelawn** [cadeyrn/bookmarks-organizer#59]
Overall, the extension works well.  Thank you!

However, the extension reports some URLs as unavailable (red dot) when they are not.  It seems to be random.  There are not particular URLs it happens with.  Running the extension immediately again (looking for broken bookmarks) will find different bookmarks as broken, and will not find previously reported broken bookmarks.

My workaround is to click on each reported broken bookmark to see if it is actually broken.  Sometimes they are... sometimes they are not.

**Comment by cadeyrn** [comment]
Hi,

I don't know how to prevent this issue. If you open a lot of bookmarks at the same time it's possible that Firefox can't connect to some of these sites. Do you have an idea?

**Comment by Gitoffthelawn** [comment]
Perhaps try this: After generating the list of "cannot connect" websites, cycle through them again, and see if they now work.

**Comment by cadeyrn** [comment]
There is already a second request if the first request fails. However, the second request follows directly after the first request so this is not ideal.

#72 will be part of the solution. The throttling mechanism should result in less false positives. The other part will be to collect all the failures and to execute the second request for each bookmark after the first check for all the other bookmarks is done.

**Comment by Gitoffthelawn** [comment]
That sounds real good.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 2.0 has been released. It contains a lot of improvements, including the throttling mechanism. Please re-test if "collect all the failures and to execute the second request for each bookmark after the first check for all the other bookmarks is done" is still necessary or if it's already good enough.

Thank you! :)

**Comment by Gitoffthelawn** [comment]
I gave it a test.  Big improvement!  Thanks! :-)

It found about 100 bookmarks that it claimed failed.  I clicked on all of them to see if they were really failures.  Of the 100 reported failures, about 90% were actual failures, and about 10% were not.

So a "double check" might be warranted.

**Comment by cadeyrn** [comment]
Thank you for testing! :)

Great to hear that the situation is much better now and good to know that more optimizations are still desirable!

**Comment by Gitoffthelawn** [comment]
You're welcome.  And thank YOU for the solid improvements so far.

**Comment by cadeyrn** [comment]
@Gitoffthelawn 

Bookmarks Organizer 3.0 has been released. Can you please check if there are more improvements needed? If there are still wrong results could you share the URLs of these bookmarks?

Thank you!

**Comment by Gitoffthelawn** [comment]
I've been testing Bookmark Organizer 3.0 for several days now.  More improvements are indeed needed for this issue, although all the improvements you made are still present, which is great.

Before I write more on this issue, I found a serious bug, and I'll type that up for you now and post it in a new issue report.

**Comment by Gitoffthelawn** [comment]
You're welcome!  Thank *you* for Bookmarks Organizer.

You're right about the site I mentioned.  I tried it about a dozen times, and half the time it loaded and half the time it didn't.
