### ISSUE TITLE
Request: Pale Moon compatibility

### ISSUE THREAD

**Issue by KNTRO** [cadeyrn/bookmarks-organizer#6]
**Sören**,

Hello! I've discovered your wonderful add-on thanks to [this post on gHacks](https://www.ghacks.net/2017/05/20/bookmarks-organizer-for-firefox/). I'd like to ask you to make this add-on compatible with the [Pale Moon web browser](http://www.palemoon.org/), please.

Thanks in advance for reading! :+1:

**Comment by cadeyrn** [comment]
Hi,

unfortunately that's not possible as Pale Moon does not support WebExtensions. By the way, Pale Moon does also not support the older add-on SDK. And the developer of Pale Moon already said that Pale Moon won't support WebExtensions in the future. So there is nothing what I can do, Pale Moon is a too bad browser.
