### ISSUE TITLE
Find bookmarks without Name: Should ignore Seperators

### ISSUE THREAD

**Issue by FabKre** [cadeyrn/bookmarks-organizer#61]
*Find bookmarks without name* lists entries for **bookmark-seperators**, because they do not have a name (they don't have data either). Thus bookmark-seperators should be ignored.

**Comment by cadeyrn** [comment]
Thank you for opening this issue. I agree.

**Comment by bunnybooboo** [comment]
Yes a user in social reached out for a dupes add-on and after my suggesting your awesome work they  flagged it as not working because of this issue and #48

**Comment by cadeyrn** [comment]
Fixed in Bookmarks Organizer 2.0.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 2.0 has been released:
https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/
