### ISSUE TITLE
The keyboard shortcut conflicts with "Clear the Web Console output"

### ISSUE THREAD

**Issue by monk-time** [cadeyrn/bookmarks-organizer#62]
A few months ago Firefox has replaced its Dev Tools with a new GUI, and with it one of the two available keyboard shortcuts for clearing the console (Alt+R) has stopped working. The other one (Ctrl+Shift+L, [added in Firefox 44](https://bugzilla.mozilla.org/show_bug.cgi?id=1162848)) is still working, but unfortunately this extension also uses it and blocks it from its native function.

I've heard it's not easily possible to change webextension shortcuts through user settings, but at least a toggle to disable this shortcut would be very much appreciated.

**Comment by cadeyrn** [comment]
Fixed in #67. Will be part of Bookmarks Organizer 2.0.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 2.0 has been released:
https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/
