### ISSUE TITLE
Firefox for Android 57

### ISSUE THREAD

**Issue by davidhedlund** [cadeyrn/bookmarks-organizer#63]
Your addon supports Firefox Quantum (Firefox 57), do you plan to add support for Firefox for Android 57 as well?

**Comment by cadeyrn** [comment]
Maybe in the future but not in the short term. It requires at least a better user interface.

**Comment by cadeyrn** [comment]
Firefox for Android does not support the Bookmarks API. Once it will be available I will reconsider.
