### ISSUE TITLE
Random bookmark

### ISSUE THREAD

**Issue by PanderMusubi** [cadeyrn/bookmarks-organizer#81]
In order explore your bookmarks in a more creative way, please offer a second toolbar button with this add-on called "random bookmark". Then a user uses this button in the toolbar, a random page is opened in a new tab. This helps a user organize or delete their bookmarks in an alternative way.

**Comment by keunes** [comment]
I'm looking for such functionality as well, and I came across the following: https://github.com/keeporsweep/keeporsweep.net/issues/5

Maybe if more people indicate their interest, we'll see a dedicated add-on for this purpose.

**Comment by cadeyrn** [comment]
Thanks for the link. I won't have the time in the next weeks but it's definitively a funny idea and something I will consider. Maybe even as standalone add-on before something similar will be merged back into the Bookmarks Organizer.

**Comment by cadeyrn** [comment]
@PanderMusubi and @keunes: I will work on a solution and share more information later this work.

**Comment by cadeyrn** [comment]
@PanderMusubi  and @keunes: I developed a new add-on for this use case:

GitHub: https://github.com/cadeyrn/keep-or-delete-bookmarks
Download: https://addons.mozilla.org/en-US/firefox/addon/keep-or-delete-bookmarks/

Have fun with this new add-on!

**Comment by cadeyrn** [comment]
Please let me know if you think that it's still needed to implement such an option directly into the Bookmarks Organizer. At the moment it would be no that easy without bigger interface changes so it would be a bigger task. In the meantime I will close this issue (can be revisisted at any time).

Thank you for your feedback.
