### ISSUE TITLE
I clicked yes to stop confirmation popups....now BO isn't working

### ISSUE THREAD

**Issue by lemonstar** [cadeyrn/bookmarks-organizer#82]
How do I undo this? I looked in popup options for FF and added 
moz-extension://3e279f09-560a-4d6b-a65c-0a35b74f8ddd/html/ui.html
to the list of sites allowed where popups are allowed but i don;t know if theses small dialogues that popup asking me for confirmation about fixing or deleting bookmarks are actually classed as popups or as something else - either way the the add-on isn't working or doing anything now having scanned my bookmarks - I guess because I stupidly - quickly without thinking - clicked on the wrong reply to a question about allowing or stopping these small dialogues poping up and asking me to confirm actions such as delete bookmark or fix bookmark.

**Comment by DaveJ61** [comment]
I have exactly the same issue. I thought that the dialog was referring to the website I wanted to delete, not this bookmarks-organizer addon.
I have searched everywhere and cannot find a solutipn, so if someone can answer this, it would be really helpful, thank you.

**Comment by Marcuse7** [comment]
Please try the following:
- close BO tab and try again
- as a try, set privacy.popups.disable_from_plugins to 2 (settings is described in http://kb.mozillazine.org/Privacy.popups.disable_from_plugins)
Good luck!

**Comment by cadeyrn** [comment]
The long term plan is to convert the browser's default confirmation dialogs with a custom solution which will be more beautiful and give me more control and allows me to prevent this kind of UX weakness.

**Comment by cadeyrn** [comment]
Fixed in Bookmarks Organizer 3.1, will be released this week.

**Comment by cadeyrn** [comment]
Bookmarks Organizer 3.1 has been released.
