### ISSUE TITLE
Deleting duplicates

### ISSUE THREAD

**Issue by CristianEmanuel** [cadeyrn/bookmarks-organizer#84]
Hello. I have more than 900 bookmarks duplicates (importing from Firefox to Chrome and to browsers from saved bookmarks done that), no option/button to delete them all at once. Is there a option to delete them all fast?
Thank you.

**Comment by cadeyrn** [comment]
Not yet. It's a duplicate of #8.

**Comment by Thomas-D-C** [comment]
> It's a duplicate of #8.

Do you mean #38 ?
Or maybe #53 ?

**Comment by cadeyrn** [comment]
Issue #8 is about seleting and deleting multiple bookmarks at once. You can also see this as a duplicate of #38 or as a subset of #53.
