### ISSUE TITLE
No option to delete all errors seen

### ISSUE THREAD

**Issue by Bob-Mc** [cadeyrn/bookmarks-organizer#85]
When I initiate a search by typing"Bookmarks Errors" at the top of my Firefox page, it does a proper search for bookmarks with errors, I don't have the option to delete all of them.

When I do a regular search, the "button" does appear, and it works. I made a screenshot of the lack of the delete all capability, but now that I see it is unique to the errrors only search, it is probably not necessary.

**Comment by cadeyrn** [comment]
Fixed in Bookmarks Organizer 3.0. Thanks for reporting.
