### ISSUE TITLE
Possibility to edit bookmark Description as well

### ISSUE THREAD

**Issue by Migliutin** [cadeyrn/bookmarks-organizer#87]
Besides `name `and `URL`, it would be nice to be able to edit `Description` field as well

**Comment by cadeyrn** [comment]
Thank you for your suggestion. The bookmark description will be removed from Firefox so this suggestion is a WONTFIX because there will be no bookmark descriptions soon.

**Comment by perdolka** [comment]
Where can I read about it?

**Comment by cadeyrn** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402890

**Comment by perdolka** [comment]
Thanks.
