### ISSUE TITLE
export/save to disk selected files/folder (feature request)

### ISSUE THREAD

**Issue by swhib** [cadeyrn/bookmarks-organizer#89]
I think of your addon as my *one* solution for bookmarks. This is why I post this request even though I'm not sure if it is out of scope.

I don't know any webextension addon that allows to export to an html file only selected files or only the results for the current search/currently shown bookmarks or a folder. I think this would be useful for many people (or did I miss another addon?)

Thanks for your great work and your attention!

**Comment by cadeyrn** [comment]
Hi,

thank you for your suggestion. At the moment the focus on Bookmarks Organizer are broken and redirect bookmarks, Bookmarks Organizer is not (yet?) an alternative view for all bookmarks. For this reason I would say this suggestion is out of scope. So I will close this ticket.

But maybe the Bookmark Organizer will be enhanced in the future to be a general bookmarks viewer. Then your suggestion makes sense and could be reconsidered.
