### ISSUE TITLE
doesn't work with zero bookmarks?

### ISSUE THREAD

**Issue by dax006** [cadeyrn/bookmarks-organizer#90]
I deleted all my bookmarks and ran your addon and it said I had all my bookmarks.
![reporting_wrong](https://user-images.githubusercontent.com/7076319/41495915-64591e76-70f8-11e8-9347-cff0366f57fb.png)

**Comment by cadeyrn** [comment]
I don't understand your request. 1,943 bookmarks are not zero bookmarks.

**Comment by dax006** [comment]
Right. But your program says zero bookmarks are 1943 bookmarks. Something’s buggy.

**Comment by cadeyrn** [comment]
There have to be bookmarks somewhere. There is nothing the add-on can do wrong. If the Bookmarks Organizer says there are 1,943 bookmarks then because the bookmarks API of Firefox finds 1,943 bookmarks.

**Comment by dax006** [comment]
Any clue why they don’t appear in my bookmarks manager? :(

**Comment by cadeyrn** [comment]
Are you sure that there are no bookmarks in "Bookmarks Toolbar", "Bookmarks Menu" and "Mobile Bookmarks"?

**Comment by cadeyrn** [comment]
closing because issue opener did not response.
