### ISSUE TITLE
Funktionalität!

### ISSUE THREAD

**Issue by longkeeler** [cadeyrn/bookmarks-organizer#91]
OK, der organizer findet bei mir in Jahrzehnten gesammelte 82.000 Bookmarks, davon 4.800 Mehrfacheinträge. Die jetzt mit einem Klick automatisch zu bereinigen, das hab ich beim addon-Namen "organizer" erwartet. Wann kommt das?

**Comment by cadeyrn** [comment]
> findet bei mir in Jahrzehnten gesammelte 82.000 Bookmarks

Dir ist hoffentlich selbst klar, dass es bei einer derart hohen Anzahl an Lesezeichen überhaupt nicht schnell gehen kann.

> Die jetzt mit einem Klick automatisch zu bereinigen, das hab ich beim addon-Namen "organizer" erwartet. Wann kommt das?

Ich kann derzeit leider keinen Zeitplan nennen. Momentan arbeite ich nicht an diesem Feature, grundsätzlich geplant ist es schon:

https://github.com/cadeyrn/bookmarks-organizer/issues/38
